name = "sween-api"
main = "server.js"
compatibility_date = "2025-03-20"

[vars]
ALLOWED_ORIGIN = "*"

[[d1_databases]]
binding = "DB"
database_name = "cakto-db"
database_id = "be049470-5b28-4847-aaae-304a697dc396"

[[kv_namespaces]]
binding = "USERS_KV"
id = "c9d8969fcd9648259ce70a2590c05679"